- type: entity
  id: LockerMedicineBrigFilled
  suffix: Filled
  parent: LockerMedicineBrig
  components:
  - type: StorageFill
    contents:
      - id: BoxSyringe
      - id: EpinephrineChemistryBottle
        amount: 3
      - id: Brutepack
        amount: 2
      - id: Ointment
        amount: 2
      - id: Bloodpack
        amount: 2
